export const todoConstants = {
  UPDATE_FETCHING: 'UPDATE_FETCHING',
  TODO_STORE_ALL: 'TODO_STORE_ALL',
  TODO_CREATED: 'TODO_CREATED',
  TODO_UPDATED: 'TODO_UPDATED',
  TODO_DELETED: 'TODO_DELETED',
  TODO_SELECTED: 'TODO_SELECTED',
  TODO_REFRESH: 'TODO_REFRESH',
  TODO_SET_META: 'TODO_SET_META',
};
